"""Added department column to Employee model

Revision ID: d03b3d935d2b
Revises: 0ee1332c1e61
Create Date: 2024-07-03 15:03:54.419511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03b3d935d2b'
down_revision = '0ee1332c1e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'department')
    # ### end Alembic commands ###
